USE DBPADRAO

CREATE TABLE TBPRODUTO(
IDPRODUTO INTEGER IDENTITY (1,1),
NOMEPRODUTO VARCHAR (50) NOT NULL,
PRECOPRODUTO DECIMAL (18,2) NOT NULL,
QUANTIAESTOQUE INTEGER NOT NULL,
QUANTIDADEMIN INTEGER NOT NULL,
DATACAD DATE NULL,
CONSTRAINT PKPRODUTO PRIMARY KEY (IDPRODUTO))

INSERT INTO TBPRODUTO VALUES
('PC', 1000.99, 2, 1, '01/01/2010'),
('TV', 2000.50, 11, 10, '09/10/2008'),
('MOUSE', 400.99, 100, 70, '02/02/2009'),
('TECLADO', 900.10, 300, 150, '11/11/2020'),
('FREEZER',1800,10,10,'01/08/2022'),
('LAVA LOUÇA',1500,10,10,'01/08/2022'),
('MICRO ONDAS',500,20,10,'01/08/2022'),
('TV 55',3000,40,15,'01/08/2022'),
('GELADEIRA',2500,10,5,'01/07/2022'),
('FOGÃO',700,30,20,'01/07/2022'),
('CELULAR',1000,50,10,'01/08/2022')



-- PESQUISA
SELECT * FROM TBPRODUTO

--É POSSÍVEL FAZER CONTA DENTRO DO SQL:
SELECT 10*12

--
SELECT 10*12 AS 'CONTA'

-- AS PODE SER OPCIONAL
SELECT 10*12 'CONTA'

--
SELECT 'PRODUTO CADASTRADO COM SUCESSO' AS 'MSG'

--PERFORMANCE RUIM POR PEGAR TUDO
SELECT * FROM TBPRODUTO

--BOA PERFORMANCE
SELECT IDPRODUTO,NOMEPRODUTO,PRECOPRODUTO,QUANTIAESTOQUE,QUANTIDADEMIN,DATACAD FROM TBPRODUTO

--DÁ PARA SELECIONAR CAMPOS ESPECÍFICOS.
SELECT NOMEPRODUTO,PRECOPRODUTO FROM TBPRODUTO

--COLOCAR NOME DIFERENTE NA APRESENTAÇÃO
SELECT NOMEPRODUTO AS 'NOME DO PRODUTO',PRECOPRODUTO AS 'PREÇO DO PRODUTO' FROM TBPRODUTO

--COLOCAR OS DADOS EM ORDENAR -- ORDER BY
SELECT NOMEPRODUTO AS 'NOME DO PRODUTO',PRECOPRODUTO AS 'PREÇO DO PRODUTO' FROM TBPRODUTO ORDER BY
NOMEPRODUTO

--COLOCAR EM ORDEM PELO SEGUNDO CAMPO DA PESQUISA -- PRECOPRODUTO
SELECT NOMEPRODUTO AS 'NOME DO PRODUTO',PRECOPRODUTO AS 'PREÇO DO PRODUTO' FROM TBPRODUTO ORDER BY
2 -- Eu selecionei o NOMEPRODUTO e PRECOPRODUTO, por isso tem 2 aqui. Se colocar 3 dá erro. Está ordenando pelo PRECOPRODUTO

--OPÇÃO PELO APELIDO DA COLUNA NOME
SELECT NOMEPRODUTO AS 'NOME',PRECOPRODUTO AS 'PREÇO' FROM TBPRODUTO ORDER BY NOME

--ORDEM ASCENDENTE ASC É OPCIONAL
SELECT NOMEPRODUTO AS 'NOME',PRECOPRODUTO AS 'PREÇO' FROM TBPRODUTO ORDER BY PRECOPRODUTO ASC
SELECT NOMEPRODUTO AS 'NOME',PRECOPRODUTO AS 'PREÇO' FROM TBPRODUTO ORDER BY PRECOPRODUTO

--ORDEM DECRESCENTE
SELECT NOMEPRODUTO AS 'NOME',PRECOPRODUTO AS 'PREÇO' FROM TBPRODUTO ORDER BY PRECOPRODUTO DESC

--ESTOQUE
SELECT NOMEPRODUTO,QUANTIAESTOQUE,QUANTIDADEMIN FROM TBPRODUTO

--CÁLCULO PARA COMPRA
SELECT NOMEPRODUTO,QUANTIAESTOQUE,QUANTIDADEMIN,QUANTIAESTOQUE-QUANTIDADEMIN AS 'QTDE' FROM
TBPRODUTO

--ODER BY
SELECT NOMEPRODUTO,QUANTIAESTOQUE,QUANTIDADEMIN,QUANTIAESTOQUE-QUANTIDADEMIN AS 'QTDE' FROM
TBPRODUTO
ORDER BY QTDE

--ORDER BY NÍVEL 2
SELECT NOMEPRODUTO,QUANTIAESTOQUE,QUANTIDADEMIN,QUANTIAESTOQUE-QUANTIDADEMIN AS 'QTDE' FROM
TBPRODUTO
ORDER BY QTDE ASC,NOMEPRODUTO ASC

--SEM USAR O APELIDO
SELECT NOMEPRODUTO,QUANTIAESTOQUE,QUANTIDADEMIN,QUANTIAESTOQUE-QUANTIDADEMIN FROM TBPRODUTO
ORDER BY QUANTIAESTOQUE-QUANTIDADEMIN ASC,NOMEPRODUTO ASC

--REGRA DE PESQUISA USANDO O WHERE
SELECT NOMEPRODUTO,QUANTIAESTOQUE,QUANTIDADEMIN,QUANTIAESTOQUE-QUANTIDADEMIN FROM TBPRODUTO
WHERE QUANTIAESTOQUE-QUANTIDADEMIN <= 5
ORDER BY QUANTIAESTOQUE-QUANTIDADEMIN ASC,NOMEPRODUTO ASC
--O output do order by no NOMEPRODUTO será nos produtos que têm quantiaestoque-quantidademin iguais

--EXEMPLO PRÁTICO DE COMO SERIA UM CÁLCULO COM DADOS DA TABELA
SELECT NOMEPRODUTO,PRECOPRODUTO,PRECOPRODUTO*0.1 AS 'ACRÉSCIMO' FROM TBPRODUTO ORDER BY NOMEPRODUTO
SELECT NOMEPRODUTO,PRECOPRODUTO,PRECOPRODUTO*1.1 AS 'NOVO PREÇO' FROM TBPRODUTO ORDER BY NOMEPRODUTO
