CREATE DATABASE BDAULAFRIB
USE BDAULAFRIB

CREATE TABLE TBPRODUTO(
IDPRODUTO INTEGER IDENTITY (1,1),
NOMEPRODUTO VARCHAR (50) NOT NULL,
PRECOPRODUTO DECIMAL (18,2) NOT NULL,
QUANTIAESTOQUE INTEGER NOT NULL,
QUANTIDADEMIN INTEGER NOT NULL,
DATACAD DATE NULL,
CONSTRAINT PKPRODUTO PRIMARY KEY (IDPRODUTO))

INSERT INTO TBPRODUTO VALUES
('PC', 1000.99, 2, 1, '01/01/2010'),
('TV', 2000.50, 11, 10, '09/10/2008'),
('MOUSE', 400.99, 100, 70, '02/02/2009'),
('TECLADO', 900.10, 300, 150, '11/11/2020'),
('FREEZER',1800,10,10,'01/08/2022'),
('LAVA LOUÇA',1500,10,10,'01/08/2022'),
('MICRO ONDAS',500,20,10,'01/08/2022'),
('TV 55',3000,40,15,'01/08/2022'),
('GELADEIRA',2500,10,5,'01/07/2022'),
('FOGÃO',700,30,20,'01/07/2022'),
('CELULAR',1000,50,10,'01/08/2022')


--A FUNÇÃO PRECISA DE UM PARÂMETRO IGUAL UM MÉTODO
--FUNÇÃO YEAR MONTH DAY
SELECT NOMEPRODUTO, DATACAD, YEAR(DATACAD) 'ANO',  DAY(DATACAD) 'DIA', MONTH(DATACAD) 'MÊS'
FROM TBPRODUTO

--FUNÇÃO SEM PARÂMETRO (GETDATE E SYSDATETIME)
SELECT GETDATE() 'DATA E HORA DO SERVIDOR' -- DATA E HORA DA MÁQUINA
SELECT SYSDATETIME() 'DATA E HORA DO SERVIDOR' -- A DIFERENÇA PARA O GETDATE() É APENAS A PRECISÃO

--DIFERENÇA DE DIAS
SELECT NOMEPRODUTO, DATACAD, DATEDIFF (DAY,DATACAD, GETDATE()) -- DÁ PARA COLOCAR UMA FUNÇÃO DENTRO DE UMA OUTRA FUNÇÃO
'DIFERENÇA DE DIAS ENTRE A DATA DE CADASTRO E HOJE' FROM TBPRODUTO

--P/ SABER DIAS VIVIDOS
SELECT DATEDIFF(DAY, '19/03/1999', GETDATE()) --PARÂMETRO É DIA INICIAL E DIA FINAL PARA CONTAR
'DIAS VIVIDOS', DATEDIFF(MONTH, '19/03/1999', GETDATE()) 'MESES VIVIDOS'

--OUTRO EXEMPLO UTILIZANDO UMA FUNÇÃO COMO PARÂMETRO PARA PUXAR O DIA, MÊS E ANO ATUAL
SELECT YEAR(GETDATE()) 'ANO ATUAL', MONTH(GETDATE()) 'MES ATUAL', DAY(GETDATE()) 'DIA ATUAL'

--VERIFICAR SE A DATA É VÁLIDA
SELECT ISDATE('09/09/2022') 'DATA VÁLIDA',
ISDATE('30/02/2022') 'DATA (30/02/2022) É VÁLIDA?'  --A FUNÇÃO É BOOLEANA, 1 = TRUE 0 = FALSE. NÃO EXISTE 30/02

--SOMAR DADOS A UMA DATA
SELECT DATEADD(YEAR,9,GETDATE()) 'DIA ATUAL + 9 ANOS FUTURO',
DATEADD (MONTH,9,GETDATE()) 'DIA ATUAL + 9 MESES FUTURO', 
DATEADD (DAY,9,GETDATE()) 'DIA ATUAL + 9 DIAS FUTURO'

SELECT NOMEPRODUTO, DATACAD, DATENAME(MONTH, DATACAD) 'NOME DO MÊS',
DATENAME(MONTH,GETDATE()) 'NOME DO MÊS ATUAL' FROM TBPRODUTO -- FUNÇÃO P/ ESPECIFICAR E SEPARAR O MÊS. MÊS ATUAL = CONSIDERA O DO SERVIDOR

--FUNÇÕES MATEMÁTICAS
SELECT PI() 'VALOR DE PI', SQRT(256) 'RAIZ QUADRADA DE 256',
SQUARE(121) '121^2', POWER(121,3) '121 A TERCEIRA POTÊNCIA'

--FUNÇÕES DE TEXTO
SELECT NOMEPRODUTO, LOWER(NOMEPRODUTO) 'NOME MINÚSCULO', 
UPPER('aula de banco de dados') 'MAIÚSCULAS'
FROM TBPRODUTO

--TAMANHO
SELECT NOMEPRODUTO,LEN(NOMEPRODUTO) AS 'QUANTIA DE DIGITOS' FROM TBPRODUTO

--MÁSCARA DE ENTRADA, CEP 00000-000.
SELECT '04515030' AS 'CEP SEM MÁSCARA' 

--SOMA E CONCATENAÇÃO
SELECT 5 + 20 'SOMA', 'AB' + 'CD' AS 'CONCATENAÇÃO' --GRUDAR TEXTO

--SUBSTRING/´MÁSCARA DE ENTRADA
SELECT '04515030' AS 'CEP SEM MÁSCARA', SUBSTRING('04515030', 1,5) 'PRIMEIRA PARTE', --1 = STRING COMEÇA NA POSIÇÃO [1] E TERMINA NA [5]
SUBSTRING('04515030', 6,3) AS 'SEGUNDA PARTE', 
SUBSTRING('04515030', 1,5) + '-' + SUBSTRING('04515030', 6,3) AS 'CEP'


--FUNÇÃO DE AGRUPAMENTO OU AGREGAÇÃO
SELECT COUNT(IDPRODUTO) AS 'CONTA', COUNT(*) AS 'CONTA USANDO *' 
FROM TBPRODUTO --QUANTAS LINHAS HÁ NA TABELA?

--FUNÇÕES PARA CÁLCULOS
SELECT COUNT(*) AS 'CONTA', MAX(PRECOPRODUTO) AS 'MAIOR PREÇO', MIN(PRECOPRODUTO) AS 'MENOR PREÇO', 
SUM(PRECOPRODUTO) 'SOMATORIA DE TODOS OS PREÇOS', AVG(PRECOPRODUTO) AS 'PREÇO MÉDIO',
SUM(PRECOPRODUTO)/COUNT(*) AS 'CÁLCULO DA MÉDIA NA MÃO'
FROM TBPRODUTO

--ERRO
SELECT NOMEPRODUTO FROM TBPRODUTO
SELECT COUNT(*) AS 'CONTA' FROM TBPRODUTO --AGRUPADO MOSTRA APENAS 1 LINHA

SELECT NOMEPRODUTO, COUNT(*) AS 'CONTA' FROM TBPRODUTO -- VAI DAR ERRO, ENTÃO DEVE SER UTILIZADO O GROUP BY.
